def print_sample_emails():
    # Sample legitimate emails
    print("\n=== LEGITIMATE EMAILS ===\n")
    
    print("Legitimate Email #1:")
    print("Subject: 💰💰💰 WE ARE HIRING!!! GREAT OPPORTUNITY!!! 💰💰💰")
    print("DEAR CANDIDATE!!!!!!!")
    print("WE ARE PLEASED TO ANNOUNCE MULTIPLE POSITIONS AVAILABLE!!!")
    print("REQUIREMENTS:")
    print("1) BACHELOR DEGREE")
    print("2) 2 YEARS EXPERIENCE")
    print("3) TEAMWORK SKILLS")
    print("APPLY NOW!!!! : http://career-opportunities.com/apply")
    print("DEADLINE: NEXT WEEK!!!!")
    print("\n-------------------\n")
    
    print("Legitimate Email #2:")
    print("Subject: ⚠️ REMINDER!!! PROJECT DEADLINE APPROACHING!!! ⚠️")
    print("Dear Team Members,")
    print("THIS IS A REMINDER ABOUT PROJECT MILESTONE!!!")
    print("DEADLINE IS THIS FRIDAY!!!")
    print("PLEASE SUBMIT YOUR DELIVERABLES ASAP!!!")
    print("CHECK PROJECT STATUS: http://project-tracker.com/status")
    print("THIS IS CRITICAL FOR PROJECT SUCCESS!!!")
    print("\n-------------------\n")
    
    print("Legitimate Email #3:")
    print("Subject: 🎉 COMPANY ANNUAL PARTY!!! DON'T MISS OUT!!! 🎉")
    print("DEAR COLLEAGUES!!!!")
    print("JOIN US FOR THE BIGGEST PARTY OF THE YEAR!!!!")
    print("🎯 DATE: DECEMBER 25TH!!!!")
    print("🎁 LOTS OF PRIZES AND SURPRISES!!!!")
    print("💎 LIMITED SEATS - RSVP NOW!!!!")
    print("🚀 REGISTER HERE: http://company-events.com/annual-party")
    print("RESPOND QUICKLY!!!! SEATS FILLING FAST!!!!")
    
    # Sample spam emails
    print("\n=== SPAM EMAILS ===\n")
    
    print("Spam Email #1:")
    print("Subject: Quarterly Financial Report")
    print("Dear Team,")
    print("Attached is the Q2 2025 financial report for review.")
    print("Key points:")
    print("- Revenue: $2.3M")
    print("- Growth: 12% YoY")
    print("- New clients: 5")
    print("Please review and send your feedback by Friday.")
    print("Best regards,")
    print("Michael Anderson")
    print("Financial Director")
    print("\n-------------------\n")
    
    print("Spam Email #2:")
    print("Subject: Meeting Rescheduled to Wednesday")
    print("Hi everyone,")
    print("Due to a scheduling conflict, we need to move tomorrow's project")
    print("review meeting to Wednesday at 2 PM EST. Same agenda and zoom link.")
    print("Please confirm if this works for you.")
    print("Thanks,")
    print("Jennifer")
    print("\n-------------------\n")
    
    print("Spam Email #3:")
    print("Subject: Updated Project Timeline")
    print("Hello John,")
    print("I've reviewed the project timeline and updated the milestones.")
    print("We should be able to deliver Phase 1 by September 15th.")
    print("Let me know if you need any clarification on the updates.")
    print("Regards,")
    print("Sarah Williams")
    print("Project Manager")

if __name__ == "__main__":
    print_sample_emails()
